### ISSUE TITLE
Argument track***() does not correspond to the method definition.

### ISSUE THREAD

**Issue by twofacauth** [ingestly/ingestly-client-javascript#21]
Argument `targetWindow` in
https://github.com/ingestly/ingestly-client-javascript/blob/40b984ad139d49d0903105b630c31a91a51c946a/src/ingestly.js#L82
is not defined in the method
https://github.com/ingestly/ingestly-client-javascript/blob/40b984ad139d49d0903105b630c31a91a51c946a/src/ingestly.js#L158

Same problem occurs in

https://github.com/ingestly/ingestly-client-javascript/blob/40b984ad139d49d0903105b630c31a91a51c946a/src/ingestly.js#L87
and
https://github.com/ingestly/ingestly-client-javascript/blob/40b984ad139d49d0903105b630c31a91a51c946a/src/ingestly.js#L168

**Comment by hjmsano** [comment]
Solved
https://github.com/ingestly/ingestly-client-javascript/pull/20
